// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41WQwArP16ICLDipmLoAibCynqd67E9s',
    appId: '1:803591186281:web:f920f09fcc0eede30bbff8',
    messagingSenderId: '803591186281',
    projectId: 'redblind-cbe11',
    authDomain: 'redblind-cbe11.firebaseapp.com',
    storageBucket: 'redblind-cbe11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADeVgssqM8UDYB86BXcfBwOuc-sM3c7L0',
    appId: '1:803591186281:android:428dfea83b4e3fb20bbff8',
    messagingSenderId: '803591186281',
    projectId: 'redblind-cbe11',
    storageBucket: 'redblind-cbe11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-y7kp4u9ni5FYz2e0rs2ulywJnaVFQg',
    appId: '1:803591186281:ios:023ec7192ab001700bbff8',
    messagingSenderId: '803591186281',
    projectId: 'redblind-cbe11',
    storageBucket: 'redblind-cbe11.firebasestorage.app',
    iosBundleId: 'com.example.redblind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5-y7kp4u9ni5FYz2e0rs2ulywJnaVFQg',
    appId: '1:803591186281:ios:023ec7192ab001700bbff8',
    messagingSenderId: '803591186281',
    projectId: 'redblind-cbe11',
    storageBucket: 'redblind-cbe11.firebasestorage.app',
    iosBundleId: 'com.example.redblind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA41WQwArP16ICLDipmLoAibCynqd67E9s',
    appId: '1:803591186281:web:3e02ebed09c0381b0bbff8',
    messagingSenderId: '803591186281',
    projectId: 'redblind-cbe11',
    authDomain: 'redblind-cbe11.firebaseapp.com',
    storageBucket: 'redblind-cbe11.firebasestorage.app',
  );
}
